"""The Golden Master: curated expectations captured from the real legacy system.

The MVP fixture is fictional VB6 and does not run, so expectations are curated
by hand from real evidence -- a database trace, a manual observation, an actual
legacy execution -- and never produced by a model. That is enforced here:

* every case must name where its expectation came from;
* a case whose evidence is missing is refused, not defaulted;
* a case marked ``confidence: low`` is loadable and reported, but it cannot
  block a verification run, because a guess must not be able to fail a build.
"""

from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml

from ..domain.enums import RuleConfidence
from ..domain.models import GoldenMasterCase

#: The only evidence sources the specification accepts for a curated case.
ACCEPTABLE_EVIDENCE = (
    "query do SGBD",
    "observação manual",
    "observacao manual",
    "execução do legado",
    "execucao do legado",
    "database trace",
    "manual observation",
    "legacy execution",
)


class GoldenMasterError(ValueError):
    """A case that cannot be trusted to describe the legacy behaviour."""


class GoldenMasterStore:
    def __init__(self, path: Path) -> None:
        self.path = path

    def load(self) -> list[GoldenMasterCase]:
        if not self.path.is_file():
            return []
        data = yaml.safe_load(self.path.read_text(encoding="utf-8")) or {}
        raw_cases = data.get("cases") if isinstance(data, dict) else data
        return [self._validate(raw) for raw in raw_cases or []]

    def save(self, cases: list[GoldenMasterCase], system_id: str, notes: str = "") -> Path:
        payload = {
            "system_id": system_id,
            "notes": notes or "Curated from real evidence. Never generated by a model.",
            "cases": [case.model_dump(mode="json", by_alias=True) for case in cases],
        }
        self.path.parent.mkdir(parents=True, exist_ok=True)
        self.path.write_text(
            yaml.safe_dump(payload, sort_keys=False, allow_unicode=True, width=100),
            encoding="utf-8",
        )
        return self.path

    @staticmethod
    def _validate(raw: dict[str, Any]) -> GoldenMasterCase:
        case = GoldenMasterCase.model_validate(raw)
        if not case.evidence:
            raise GoldenMasterError(
                f"case {case.id} declares no evidence source; a case that cannot say "
                f"where its expectation came from is a guess"
            )
        if case.evidence.strip().lower() not in ACCEPTABLE_EVIDENCE:
            raise GoldenMasterError(
                f"case {case.id} has evidence {case.evidence!r}, which is not one of "
                f"the accepted sources: {', '.join(sorted(set(ACCEPTABLE_EVIDENCE)))}"
            )
        if not case.expected and not case.legacy_output and not case.state_trace:
            raise GoldenMasterError(f"case {case.id} expects nothing at all")
        return case


def load_cases(path: Path) -> list[GoldenMasterCase]:
    return GoldenMasterStore(path).load()


def blocking_cases(cases: list[GoldenMasterCase]) -> list[GoldenMasterCase]:
    """Cases allowed to fail a run.

    ``confidence: low`` means "possibly a guess"; such a case is compared and
    reported, but it must not decide pass/fail on its own.
    """
    return [c for c in cases if c.confidence is not RuleConfidence.LOW]


def advisory_cases(cases: list[GoldenMasterCase]) -> list[GoldenMasterCase]:
    return [c for c in cases if c.confidence is RuleConfidence.LOW]
